### ISSUE TITLE
Package archived even though original errors were previously fixed

### ISSUE THREAD

**Issue by wlandau** [cranchange/cran_histories#10]
When version 0.3.0 of [`targets`](https://docs.ropensci.org/targets/) reached CRAN on 2021-03-27, the Solaris checks produced errors because the [`arrow`](https://CRAN.R-project.org/package=arrow) package was not installed on that platform. I got an email that day:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_targets.html>.
> 
> Please correct before 2021-04-10 to safely retain your package on CRAN.
> 
> The CRAN Team

Totally reasonable. I submitted a patch immediately, it was accepted on 2021-03-28, and the Solaris error went away. For the next several weeks, including 2021-04-10, there were no errors. 

Then on 2021-04-22, I submitted version 0.4.1, which generated a new and completely different set of timestamp-related errors that I have only ever seen on CRAN machines. The following Sunday (2021-04-25) `targets` was archived without notice as if I had never fixed the `arrow`-related errors in version 0.3.0 with version 0.3.1.

> Version 0.4-1 is still failing on macOS so it and tarchetypes have been
> archived.
> 
> A recheck on my own Intel Mac today gives the same check ERRORs as
> reported on the CRAN results page.
> 
> Do not submit again without reproducing this error and confirming it has
> been corrected.

**Comment by wlandau** [comment]
Related: https://github.com/ropensci/targets/issues/434

**Comment by llrs** [comment]
Thanks for opening this issue! 
Copying also from [twitter](https://twitter.com/wmlandau/status/1386430170861424645) the summary:

> 1. 3/25: v0.3.0 CRAN Solaris errors.
> 2. 3/27: email to fix (1) by 4/10 to avoid archival.
> 3. 3/28: v0.3.1 fixes errors.
> 4. 4/10: No errors.
> 5. 4/22: v0.4.1 on CRAN. New errors, my fault.
> 6. 4/25: email reply to (2) that {targets} is "still failing" and thus archived.
