### ISSUE TITLE
A positive interaction: correcting tarchetypes

### ISSUE THREAD

**Issue by wlandau** [cranchange/cran_histories#12]
Not sure if you are also collecting positive interactions with CRAN gatekeepers, but there are a couple noteworthy ones I would like to share.

On 2021-02-01, I submitted version 0.0.3 of [`tarchetypes`](https://docs.ropensci.org/tarchetypes/). Some tests were failing because Pandoc was not available on some of the platforms. I promptly received this email:

> So you only use pandoc conditionally on its availability now?

I responded:

> That is part of what I was trying to do by skipping on Solaris. Should I resubmit with explicit checks for pandoc in the tests?

The reply:

> Yes, please, Solaris is just one example where pandoc in unavailable,
> other commercial unixes or installations may suffer the same problem.
> 
> Best,
> Uwe Ligges

I fixed and resubmitted `tarchetypes` immediately, it was quickly accepted, and all was well. An amicable ending with no archived packages. I love working with Uwe when I have the chance.

**Comment by llrs** [comment]
So far, I have only collected negative interactions. This was mostly to address and improve current friction points, and because it is more easier to find. But definitely this is also nice to record, thanks! I'll add one or two I have had.

**Comment by wlandau** [comment]
Thanks!
