### ISSUE TITLE
Positive Interaction: Dr. Gennadiy Starostin writes good email

### ISSUE THREAD

**Issue by pachadotdev** [cranchange/cran_histories#14]
I maintain 2 CRAN mirrors, and Dr. Starostin sent me an email written in very good terms, where I was asked to provide a public ssh key for secure rsync. I give him/her a star.

**Comment by llrs** [comment]
Many thanks for you addition! (and for maintaining CRAN mirrors!!)  
I do not recognize that name and couldn't find it on the [R-core members](https://www.r-project.org/contributors.html). Is this person related to CRAN maintenance or to R source code or CRAN policies?

**Comment by pachadotdev** [comment]
hi 
I have no idea, but he/she (no signature on the email) has replied a few emails regarding the mirrors
![image](https://user-images.githubusercontent.com/10091065/116836571-035f8300-ab95-11eb-8d5f-9189162ab7f7.png)

**Comment by llrs** [comment]
Ok, thanks! I assume they are not R core members but help maintaining CRAN servers. Will leave the issue open
