### ISSUE TITLE
CRAN modifying package source code without notification and introducing problems

### ISSUE THREAD

**Issue by MilesMcBain** [cranchange/cran_histories#20]
The example I watched unfold in real time was `{reprex}`. It was held in violation of policy about clipboards, which changed underneath it. The maintainers tried to negotiate a timeline for a fix, but CRAN refused. Eventually CRAN modified the package source to disable core features that used the clipboard without bumping the package version, and without notifying users (not sure about maintainers).

So suddenly the package just stopped working for people who installed it after that time, and the project was swamped by bug reports.

I am also aware of this unanswered mailing-list post suggesting this was not an isolated incident: https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003835.html

**Comment by llrs** [comment]
See the next email there are many changes (~20) on several other packages: https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003843.html

(Un)Surprisingly it didn't get any reply from CRAN maintainers.
