### ISSUE TITLE
Add disclaimer if conversation was posted in the name of somebody / anonymously

### ISSUE THREAD

**Issue by pat-s** [cranchange/cran_histories#22]
To make clear that the issue poster is not the person who was involved in this conversation.

**Comment by llrs** [comment]
I added a note on the README: https://github.com/cranchange/cran_histories/blob/main/README.md

**Comment by llrs** [comment]
Hi @pat-s, I did another round of review on the README. Do you think this is enough or should it be on an issue template?

**Comment by pat-s** [comment]
Thanks!

I think an issue template could certainly help here but I also think that the use of the "discussions" features (as mentioned in https://github.com/cranchange/cran_change.org/issues/14) could help here. Specifically because discussions can be upvoted and this could give some reflection on (generic) issues/convos that occur most often.
