### ISSUE TITLE
Require some initial context for each convo?

### ISSUE THREAD

**Issue by pat-s** [cranchange/cran_histories#23]
Like one or two sentences, briefly explaining the context behind the conversation (which might sometimes be needed / sometimes not to understand the issue).

So that the context becomes more clear and people can better relate why some conversation might have felt offensive.

**Comment by llrs** [comment]
Sometimes there is no more context than what it is already provided (specially if it is from twitter). Of course, more context is always better on the histories. Perhaps an issue template could be done for number of submissions for the new version, or the number of emails exchanged, number of CRAN administrators involved.... 
 
The conversations don't need to be offensive (hope they aren't any), the current practice uses positive and negative labels to describe the perceived tone of the exchange.

**Comment by pat-s** [comment]
Sure, not easy. I was/am just wondering that without a context some submissions might be hard to understand. But maybe this is unavoidable in some cases.

Thanks!
