### ISSUE TITLE
Make use of "discussions" tab instead of issues?

### ISSUE THREAD

**Issue by pat-s** [cranchange/cran_histories#25]
I was wondering if this might eventually be a better tool for the collection of chat histories than the "issues" tab.

**Comment by llrs** [comment]
Moved the issue, but I cannot create/open the Discussions tab @MilesMcBain

**Comment by MilesMcBain** [comment]
Sorry @llrs, your admin rights were lost when we transferred this repo. You should be an admin again now, and should be able to access all settings including enabling discussions.

**Comment by pat-s** [comment]
Thanks guys. I really think the discussions feature could work well for this. How about converting one/some issues to a discussion to see how it goes? 

Maybe a pinned issue stating to use "discussion" instead of issues here might also be helpful to users.

**Comment by llrs** [comment]
I enabled the discussion and started moving some issues there, but I have to do it manually for each issue (and it is slow). I updated the README to point where to write the ~~issues~~ discussions.

**Comment by pat-s** [comment]
Great thanks! Given the upvote potential and the categorization, this looks really great imo.

Closing here then, thanks for your work!
